---
- hosts: localhost
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    # https://hub.docker.com/r/ansible/ansible
    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    # https://docs.ansible.com/ansible/2.9/modules/docker_container_module.html
    - name: Create Portainer
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        published_ports: ["8080:8080"]
        restart_policy: "unless-stopped"
        # command: "{{ default_container_command }}"
        state: started
    #   with_sequence: count={{ create_containers }}